export interface AchievementDefinition {
  code: string;
  name: string;
  description: string;
  icon: string;
  category: 'attendance' | 'diversity' | 'loyalty' | 'special';
  requirementType: 'count' | 'specific' | 'streak';
  requirementValue: Record<string, unknown>;
  points: number;
  rarity: 'common' | 'uncommon' | 'rare' | 'epic' | 'legendary';
}

export const ACHIEVEMENTS: AchievementDefinition[] = [
  // ===== ATTENDANCE ACHIEVEMENTS =====
  // Common (easy to get early)
  {
    code: 'first_game',
    name: 'First Timer',
    description: 'Attend your first sporting event',
    icon: 'flag',
    category: 'attendance',
    requirementType: 'count',
    requirementValue: { count: 1 },
    points: 10,
    rarity: 'common',
  },
  {
    code: 'three_games',
    name: 'Getting Started',
    description: 'Attend 3 sporting events',
    icon: 'footsteps',
    category: 'attendance',
    requirementType: 'count',
    requirementValue: { count: 3 },
    points: 15,
    rarity: 'common',
  },
  {
    code: 'five_games',
    name: 'Regular Goer',
    description: 'Attend 5 sporting events',
    icon: 'ticket',
    category: 'attendance',
    requirementType: 'count',
    requirementValue: { count: 5 },
    points: 20,
    rarity: 'common',
  },
  {
    code: 'ten_games',
    name: 'Dedicated',
    description: 'Attend 10 sporting events',
    icon: 'bookmark',
    category: 'attendance',
    requirementType: 'count',
    requirementValue: { count: 10 },
    points: 30,
    rarity: 'common',
  },
  // Uncommon
  {
    code: 'twenty_five_games',
    name: 'True Fan',
    description: 'Attend 25 sporting events',
    icon: 'star',
    category: 'attendance',
    requirementType: 'count',
    requirementValue: { count: 25 },
    points: 50,
    rarity: 'uncommon',
  },
  {
    code: 'weekly_streak_2',
    name: 'Two Week Warrior',
    description: 'Attend at least one event per week for 2 weeks',
    icon: 'calendar',
    category: 'attendance',
    requirementType: 'streak',
    requirementValue: { weeks: 2 },
    points: 25,
    rarity: 'uncommon',
  },
  {
    code: 'weekly_streak_4',
    name: 'Monthly Regular',
    description: 'Attend at least one event per week for 4 weeks',
    icon: 'calendar',
    category: 'attendance',
    requirementType: 'streak',
    requirementValue: { weeks: 4 },
    points: 50,
    rarity: 'uncommon',
  },
  // Rare
  {
    code: 'fifty_games',
    name: 'Super Fan',
    description: 'Attend 50 sporting events',
    icon: 'trophy',
    category: 'attendance',
    requirementType: 'count',
    requirementValue: { count: 50 },
    points: 100,
    rarity: 'rare',
  },
  {
    code: 'monthly_streak_3',
    name: 'Quarter Year Champ',
    description: 'Attend at least one event per month for 3 months',
    icon: 'calendar-outline',
    category: 'attendance',
    requirementType: 'streak',
    requirementValue: { months: 3 },
    points: 60,
    rarity: 'rare',
  },
  {
    code: 'monthly_streak_6',
    name: 'Half Year Hero',
    description: 'Attend at least one event per month for 6 months',
    icon: 'calendar-outline',
    category: 'attendance',
    requirementType: 'streak',
    requirementValue: { months: 6 },
    points: 100,
    rarity: 'rare',
  },
  // Epic
  {
    code: 'hundred_games',
    name: 'Living Legend',
    description: 'Attend 100 sporting events',
    icon: 'medal',
    category: 'attendance',
    requirementType: 'count',
    requirementValue: { count: 100 },
    points: 250,
    rarity: 'epic',
  },
  {
    code: 'yearly_attendance',
    name: 'Year-Round Fan',
    description: 'Attend at least one event per month for a full year',
    icon: 'sunny',
    category: 'attendance',
    requirementType: 'streak',
    requirementValue: { months: 12 },
    points: 200,
    rarity: 'epic',
  },
  // Legendary
  {
    code: 'two_fifty_games',
    name: 'Hall of Famer',
    description: 'Attend 250 sporting events',
    icon: 'ribbon',
    category: 'attendance',
    requirementType: 'count',
    requirementValue: { count: 250 },
    points: 500,
    rarity: 'legendary',
  },
  {
    code: 'five_hundred_games',
    name: 'Ultimate Fan',
    description: 'Attend 500 sporting events',
    icon: 'diamond',
    category: 'attendance',
    requirementType: 'count',
    requirementValue: { count: 500 },
    points: 1000,
    rarity: 'legendary',
  },

  // ===== DIVERSITY ACHIEVEMENTS =====
  // Common
  {
    code: 'two_sports',
    name: 'Trying New Things',
    description: 'Attend events in 2 different sports',
    icon: 'shuffle',
    category: 'diversity',
    requirementType: 'count',
    requirementValue: { sports: 2 },
    points: 15,
    rarity: 'common',
  },
  {
    code: 'multi_sport',
    name: 'Sports Sampler',
    description: 'Attend events in 3 different sports',
    icon: 'apps',
    category: 'diversity',
    requirementType: 'count',
    requirementValue: { sports: 3 },
    points: 30,
    rarity: 'common',
  },
  {
    code: 'two_venues',
    name: 'Venue Visitor',
    description: 'Attend events at 2 different venues',
    icon: 'navigate',
    category: 'diversity',
    requirementType: 'count',
    requirementValue: { venues: 2 },
    points: 15,
    rarity: 'common',
  },
  {
    code: 'five_teams',
    name: 'Team Spotter',
    description: 'Watch 5 different teams play',
    icon: 'eye',
    category: 'diversity',
    requirementType: 'count',
    requirementValue: { teams: 5 },
    points: 25,
    rarity: 'common',
  },
  // Uncommon
  {
    code: 'all_rounder',
    name: 'All-Rounder',
    description: 'Attend events in 5 different sports',
    icon: 'grid',
    category: 'diversity',
    requirementType: 'count',
    requirementValue: { sports: 5 },
    points: 75,
    rarity: 'uncommon',
  },
  {
    code: 'venue_explorer',
    name: 'Venue Explorer',
    description: 'Attend events at 5 different venues',
    icon: 'location',
    category: 'diversity',
    requirementType: 'count',
    requirementValue: { venues: 5 },
    points: 40,
    rarity: 'uncommon',
  },
  {
    code: 'team_variety',
    name: 'Team Watcher',
    description: 'Watch 10 different teams play',
    icon: 'people',
    category: 'diversity',
    requirementType: 'count',
    requirementValue: { teams: 10 },
    points: 50,
    rarity: 'uncommon',
  },
  // Rare
  {
    code: 'stadium_hopper',
    name: 'Stadium Hopper',
    description: 'Attend events at 10 different venues',
    icon: 'map',
    category: 'diversity',
    requirementType: 'count',
    requirementValue: { venues: 10 },
    points: 100,
    rarity: 'rare',
  },
  {
    code: 'sports_enthusiast',
    name: 'Sports Enthusiast',
    description: 'Attend events in 7 different sports',
    icon: 'fitness',
    category: 'diversity',
    requirementType: 'count',
    requirementValue: { sports: 7 },
    points: 100,
    rarity: 'rare',
  },
  {
    code: 'team_collector',
    name: 'Team Collector',
    description: 'Watch 25 different teams play',
    icon: 'albums',
    category: 'diversity',
    requirementType: 'count',
    requirementValue: { teams: 25 },
    points: 100,
    rarity: 'rare',
  },
  // Epic
  {
    code: 'venue_master',
    name: 'Venue Master',
    description: 'Attend events at 20 different venues',
    icon: 'globe',
    category: 'diversity',
    requirementType: 'count',
    requirementValue: { venues: 20 },
    points: 200,
    rarity: 'epic',
  },
  {
    code: 'sports_connoisseur',
    name: 'Sports Connoisseur',
    description: 'Attend events in 10 different sports',
    icon: 'planet',
    category: 'diversity',
    requirementType: 'count',
    requirementValue: { sports: 10 },
    points: 200,
    rarity: 'epic',
  },
  // Legendary
  {
    code: 'world_traveler',
    name: 'World Traveler',
    description: 'Attend events at 50 different venues',
    icon: 'airplane',
    category: 'diversity',
    requirementType: 'count',
    requirementValue: { venues: 50 },
    points: 500,
    rarity: 'legendary',
  },

  // ===== LOYALTY ACHIEVEMENTS =====
  // Common
  {
    code: 'team_loyal_2',
    name: 'Team Follower',
    description: 'Attend 2 games for the same team',
    icon: 'heart-outline',
    category: 'loyalty',
    requirementType: 'count',
    requirementValue: { sameTeam: 2 },
    points: 15,
    rarity: 'common',
  },
  {
    code: 'home_ground_2',
    name: 'Familiar Grounds',
    description: 'Attend 2 events at the same venue',
    icon: 'home-outline',
    category: 'loyalty',
    requirementType: 'count',
    requirementValue: { sameVenue: 2 },
    points: 15,
    rarity: 'common',
  },
  {
    code: 'team_loyal_5',
    name: 'Loyal Supporter',
    description: 'Attend 5 games for the same team',
    icon: 'heart',
    category: 'loyalty',
    requirementType: 'count',
    requirementValue: { sameTeam: 5 },
    points: 35,
    rarity: 'common',
  },
  {
    code: 'home_ground',
    name: 'Home Ground Advantage',
    description: 'Attend 5 events at the same venue',
    icon: 'home',
    category: 'loyalty',
    requirementType: 'count',
    requirementValue: { sameVenue: 5 },
    points: 30,
    rarity: 'common',
  },
  // Uncommon
  {
    code: 'team_loyal_10',
    name: 'Die-Hard Fan',
    description: 'Attend 10 games for the same team',
    icon: 'heart-circle',
    category: 'loyalty',
    requirementType: 'count',
    requirementValue: { sameTeam: 10 },
    points: 75,
    rarity: 'uncommon',
  },
  {
    code: 'home_ground_10',
    name: 'Regular at the Ground',
    description: 'Attend 10 events at the same venue',
    icon: 'business',
    category: 'loyalty',
    requirementType: 'count',
    requirementValue: { sameVenue: 10 },
    points: 60,
    rarity: 'uncommon',
  },
  // Rare
  {
    code: 'team_loyal_25',
    name: 'Season Ticker',
    description: 'Attend 25 games for the same team',
    icon: 'shield',
    category: 'loyalty',
    requirementType: 'count',
    requirementValue: { sameTeam: 25 },
    points: 150,
    rarity: 'rare',
  },
  {
    code: 'home_ground_25',
    name: 'Venue Regular',
    description: 'Attend 25 events at the same venue',
    icon: 'storefront',
    category: 'loyalty',
    requirementType: 'count',
    requirementValue: { sameVenue: 25 },
    points: 120,
    rarity: 'rare',
  },
  // Epic
  {
    code: 'team_loyal_50',
    name: 'True Believer',
    description: 'Attend 50 games for the same team',
    icon: 'shield-checkmark',
    category: 'loyalty',
    requirementType: 'count',
    requirementValue: { sameTeam: 50 },
    points: 300,
    rarity: 'epic',
  },
  // Legendary
  {
    code: 'team_loyal_100',
    name: 'Lifelong Fan',
    description: 'Attend 100 games for the same team',
    icon: 'shield-half',
    category: 'loyalty',
    requirementType: 'count',
    requirementValue: { sameTeam: 100 },
    points: 500,
    rarity: 'legendary',
  },

  // ===== SPECIAL ACHIEVEMENTS =====
  // Common
  {
    code: 'derby_day',
    name: 'Derby Day',
    description: 'Attend a local derby match',
    icon: 'flash-outline',
    category: 'special',
    requirementType: 'specific',
    requirementValue: { matchType: 'derby' },
    points: 25,
    rarity: 'common',
  },
  {
    code: 'night_game',
    name: 'Night Owl',
    description: 'Attend an evening event (after 6pm)',
    icon: 'moon',
    category: 'special',
    requirementType: 'specific',
    requirementValue: { timeOfDay: 'evening' },
    points: 15,
    rarity: 'common',
  },
  // Uncommon
  {
    code: 'australian_open',
    name: 'Aussie Open Attendee',
    description: 'Attend an Australian Open match',
    icon: 'tennisball',
    category: 'special',
    requirementType: 'specific',
    requirementValue: { competition: 'Australian Open' },
    points: 50,
    rarity: 'uncommon',
  },
  {
    code: 'finals_game',
    name: 'Finals Bound',
    description: 'Attend a finals game',
    icon: 'trending-up',
    category: 'special',
    requirementType: 'specific',
    requirementValue: { round: 'Finals' },
    points: 40,
    rarity: 'uncommon',
  },
  {
    code: 'international_match',
    name: 'International Stage',
    description: 'Attend an international match',
    icon: 'flag',
    category: 'special',
    requirementType: 'specific',
    requirementValue: { matchType: 'international' },
    points: 50,
    rarity: 'uncommon',
  },
  // Rare
  {
    code: 'finals_series',
    name: 'Finals Fever',
    description: 'Attend 3 finals games in a season',
    icon: 'flame',
    category: 'special',
    requirementType: 'count',
    requirementValue: { finalsGames: 3 },
    points: 75,
    rarity: 'rare',
  },
  {
    code: 'boxing_day_test',
    name: 'Boxing Day Regular',
    description: 'Attend the Boxing Day Test at the MCG',
    icon: 'gift',
    category: 'special',
    requirementType: 'specific',
    requirementValue: { event: 'boxing_day_test' },
    points: 50,
    rarity: 'rare',
  },
  {
    code: 'ashes_test',
    name: 'Ashes Witness',
    description: 'Attend an Ashes Test match',
    icon: 'bonfire',
    category: 'special',
    requirementType: 'specific',
    requirementValue: { competition: 'Ashes' },
    points: 75,
    rarity: 'rare',
  },
  {
    code: 'state_of_origin',
    name: 'Origin Hero',
    description: 'Attend a State of Origin match',
    icon: 'flash',
    category: 'special',
    requirementType: 'specific',
    requirementValue: { competition: 'State of Origin' },
    points: 60,
    rarity: 'rare',
  },
  {
    code: 'world_cup',
    name: 'World Cup Witness',
    description: 'Attend a World Cup match (any sport)',
    icon: 'earth',
    category: 'special',
    requirementType: 'specific',
    requirementValue: { competition: 'World Cup' },
    points: 75,
    rarity: 'rare',
  },
  // Epic
  {
    code: 'grand_final',
    name: 'Grand Finalist',
    description: 'Attend a Grand Final',
    icon: 'trophy',
    category: 'special',
    requirementType: 'specific',
    requirementValue: { round: 'Grand Final' },
    points: 100,
    rarity: 'epic',
  },
  {
    code: 'championship_game',
    name: 'Championship Day',
    description: 'Attend a championship/title decider',
    icon: 'trophy-outline',
    category: 'special',
    requirementType: 'specific',
    requirementValue: { round: 'Championship' },
    points: 100,
    rarity: 'epic',
  },
  {
    code: 'multiple_grand_finals',
    name: 'Finals Regular',
    description: 'Attend 3 Grand Finals',
    icon: 'podium',
    category: 'special',
    requirementType: 'count',
    requirementValue: { grandFinals: 3 },
    points: 200,
    rarity: 'epic',
  },
  // Legendary
  {
    code: 'olympic_event',
    name: 'Olympic Spirit',
    description: 'Attend an Olympic event',
    icon: 'medal-outline',
    category: 'special',
    requirementType: 'specific',
    requirementValue: { competition: 'Olympics' },
    points: 250,
    rarity: 'legendary',
  },
  {
    code: 'super_bowl',
    name: 'Super Bowl Sunday',
    description: 'Attend a Super Bowl',
    icon: 'american-football',
    category: 'special',
    requirementType: 'specific',
    requirementValue: { event: 'super_bowl' },
    points: 300,
    rarity: 'legendary',
  },
];

export const RARITY_COLORS = {
  common: '#9ca3af',
  uncommon: '#22c55e',
  rare: '#3b82f6',
  epic: '#8b5cf6',
  legendary: '#f59e0b',
} as const;

export const CATEGORY_ICONS = {
  attendance: 'ticket',
  diversity: 'apps',
  loyalty: 'heart',
  special: 'star',
} as const;

export function getAchievementByCode(code: string): AchievementDefinition | undefined {
  return ACHIEVEMENTS.find((a) => a.code === code);
}

export function getAchievementsByCategory(
  category: AchievementDefinition['category']
): AchievementDefinition[] {
  return ACHIEVEMENTS.filter((a) => a.category === category);
}

export function getRarityColor(rarity: AchievementDefinition['rarity']): string {
  return RARITY_COLORS[rarity];
}
